language: cpp
os:
    - linux
    - osx
compiler:
    - g++

script:
    - cd test
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PROJECT_HOME=/home/travis/build/redfieldcd/helloCpp; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PROJECT_HOME=/Users/travis/build/redfieldcd/helloCpp; fi
    - make clean
    - make
    - ./testVector

